export default actionType = {
    LOGIN_REQUEST :'LOGIN_REQUEST',
    LOGIN_SUCCEED :'LOGIN_SUCCEED',
    SIGNUP_REQUEST :'SIGNUP_REQUEST',
    SIGNUP_SUCCEED :'SIGNUP_SUCCEED',
    IS_ERROR :'IS_ERROR',
}